#ifndef _LNG_H
#define _LNG_H

#define psz_savestate	"Save last panels state"
#define psz_backexit	"Back in root - Exit"
#define psz_sconchk		"Move cursor down on check"
#define psz_loopnav		"Enable loop navigation"

#define psz_scspeed		"Text scroll speed"
#define psz_scwait		"Text scroll wait"
#define psz_useboldf	"Use bold font"

#define psz_loadicons	"Load mcfileico.cfg"
#define psz_loadkeys	"Load mckeys.cfg"
#define psz_loadmui		"Load default.mclg"
#define psz_loadcs		"Load default.mccs"
#define psz_configpath	"mcconfig.cfg path"

#define psz_showhiddrv	"Show hidden drives"
#define psz_showmmc		"Show MMC"
#define psz_showhidden	"Show hidden files"
#define psz_showsystem	"Show system files"

#define psz_confirmexit	"On exit"
#define psz_confirmdel	"On delete"
#define psz_confirmdelr	"On delete readonly"
#define psz_confirmcopy	"On copy"
#define psz_confirmmove	"On move"
#define psz_confirmrepl	"On replace"

#define psz_autoexit_after			"AutoExit after (min)"
#define psz_autoexit_on_background	"AutoExit on background"

#define psz_zip_enable		"Enable zip support"
#define psz_zip_detect_by	"Detect zip by"
#define psz_temppath		"Path for temp files"
#define psz_cleartemp		"Delete temp files on exit"

#define psz_about		"mc v"version" \n(c) 2007 weclnt, greengo7\nThanks for efficient advices: Aru55, 1nvisible, captain_SISka"

#define psz_no			"No"
#define psz_yes			"Yes"

#define psz_content		"Content"
#define psz_extension	"Extension"

#define psz_drv_0		"Data"
#define psz_drv_1		"Cache"
#define psz_drv_2		"Config"
#define psz_drv_4		"MMC"

#define psz_mcvol		"MC"
#define psz_zipvol		"ZIP"

#define psz_errfile		"?"

#define psz_sm_common	"Common"
#define psz_sm_confirms	"Confirmations"
#define psz_sm_configs	"Configs"
#define psz_sm_disks	"Disks and files"
#define psz_sm_gui		"GUI"
#define psz_sm_autoexit	"AutoExit"
#define psz_sm_zip		"Zip"


#define sz_no			"§¯§Ö§ä"
#define sz_yes			"§¥§Ñ"

#define sz_byte			"§Ò"
#define sz_kbyte		"§¬§Ò"
#define sz_mbyte		"§®§Ò"

#define sz_reconfig		"§¬§à§ß§æ§Ú§Ô§å-\n§â§Ñ§è§Ú§ñ §à§Ò§ß§à§Ó§Ý§Ö§ß§Ñ!"
#define sz_lng			"§Á§Ù§í§Ü"
#define sz_lngname		"§²§å§ã§ã§Ü§Ú§Û"

#define sz_dirmking		"§³§à§Ù§Õ§Ñ§ß§Ú§Ö §á§Ñ§á§à§Ü"
#define sz_copying		"§¬§à§á§Ú§â§à§Ó§Ñ§ß§Ú§Ö"
#define sz_moveing		"§±§Ö§â§Ö§Þ§Ö§ë§Ö§ß§Ú§Ö"
#define sz_deling		"§µ§Õ§Ñ§Ý§Ö§ß§Ú§Ö"

#define sz_mcmenu		"§®§Ö§ß§ð MC"
#define sz_select		"§£§í§Ò§à§â"
#define sz_back			"§¯§Ñ§Ù§Ñ§Õ"

#define sz_open			"§°§ä§Ü§â§í§ä§î"
#define sz_file_m		"§¶§Ñ§Û§Ý..."
#define sz_chk				"§£§í§Õ§Ö§Ý§Ú§ä§î"
#define sz_chkall			"§£§í§Õ§Ö§Ý§Ú§ä§î §Ó§ã§Ö"
#define sz_invchk			"§ª§ß§Ó§Ö§â§ä§Ú§â§à§Ó§Ñ§ä§î"
#define sz_unchall			"§³§Ò§â§à§ã§Ú§ä§î §Ó§ã§Ö"
#define sz_oper_m		"§°§á§Ö§â§Ñ§è§Ú§Ú..."
#define sz_past				"§£§ã§ä§Ñ§Ó§Ú§ä§î"
#define sz_cancel			"§°§ä§Þ§Ö§ß§Ú§ä§î"
#define sz_copy				"§¬§à§á§Ú§â§à§Ó§Ñ§ä§î"
#define sz_move				"§±§Ö§â§Ö§Þ§Ö§ã§ä§Ú§ä§î"
#define sz_del				"§µ§Õ§Ñ§Ý§Ú§ä§î"
#define sz_rename			"§±§Ö§â§Ö§Ú§Þ§Ö§ß§à§Ó§Ñ§ä§î"
#define sz_newdir			"§¯§à§Ó§Ñ§ñ §á§Ñ§á§Ü§Ñ"
#define sz_newfile			"§¯§à§Ó§í§Û §æ§Ñ§Û§Ý"
#define sz_prop			"§³§Ó§à§Û§ã§ä§Ó§Ñ"
#define sz_view_m		"§£§Ú§Õ..."
#define sz_sort_m			"§³§à§â§ä§Ú§â§à§Ó§Ü§Ñ..."
#define sz_sortn				"§±§à §Ú§Þ§Ö§ß§Ú"
#define sz_sorte				"§±§à §ä§Ú§á§å"
#define sz_sorts				"§±§à §â§Ñ§Ù§Þ§Ö§â§å"
#define sz_sortd				"§±§à §Õ§Ñ§ä§Ö"
#define sz_sortr				"§°§Ò§â§Ñ§ä§ß§Ñ§ñ"
#define sz_filter			"§¶§Ú§Ý§î§ä§â"
#define sz_refresh			"§°§Ò§ß§à§Ó§Ú§ä§î"
#define sz_misc_m		"§²§Ñ§Ù§ß§à§Ö..."
#define sz_bm_m				"§©§Ñ§Ü§Ý§Ñ§Õ§Ü§Ú..."
#define sz_add					"§¥§à§Ò§Ñ§Ó§Ú§ä§î"
#define sz_bml					"§³§á§Ú§ã§à§Ü"
#define sz_drvinf			"§¥§Ú§ã§Ü§Ú"
#define sz_settings			"§¯§Ñ§ã§ä§â§à§Û§Ü§Ú"
#define sz_about_m			"§°§Ò §ï§Ý§î§æ§Ö..."
#define sz_exit			"§£§í§ç§à§Õ"

#define sz_bm			"§©§Ñ§Ü§Ý§Ñ§Õ§Ü§Ñ"

#define sz_name			"§ª§Þ§ñ"
#define sz_fullname		"§±§à§Ý§ß§à§Ö §Ú§Þ§ñ"
#define sz_size			"§²§Ñ§Ù§Þ§Ö§â"
#define sz_global		"§°§Ò§ë§Ú§Û"
#define sz_folders		"§±§Ñ§á§à§Ü"
#define sz_files		"§¶§Ñ§Û§Ý§à§Ó"
#define sz_date			"§¥§Ñ§ä§Ñ §ã§à§Ù§Õ§Ñ§ß§Ú§ñ"
#define sz_attr			"§¡§ä§â§Ú§Ò§å§ä§í"
#define sz_readonly		"§´§à§Ý§î§Ü§à §é§ä§Ö§ß§Ú§Ö"
#define sz_hidden		"§³§Ü§â§í§ä§í§Û"
#define sz_system		"§³§Ú§ã§ä§Ö§Þ§ß§í§Û"
#define sz_arh			"§¡§â§ç§Ú§Ó§ß§í§Û"
#define sz_subdirs		"§°§Ò§â§Ñ§Ò§Ñ§ä§í§Ó§Ñ§ä§î §á§à§Õ§Ü§Ñ§ä§Ñ§Ý§à§Ô§Ú"
#define sz_ncsize		"§¯§Ö§ã§Ø§Ñ§ä§í§Û"
#define sz_csize		"§³§Ø§Ñ§ä§í§Û"
#define sz_cglobal		"§°§Ò§ë§Ú§Û §ã§Ø§Ñ§ä§í§Û"

#define sz_pmt_del		"§µ§Õ§Ñ§Ý§Ú§ä§î?"
#define sz_pmt_rodel	"§¶§Ñ§Û§Ý %s §ä§à§Ý§î§Ü§à §Õ§Ý§ñ §é§ä§Ö§ß§Ú§ñ.\n§µ§Õ§Ñ§Ý§Ú§ä§î?"
#define sz_pmt_copy		"§¬§à§á§Ú§â§à§Ó§Ñ§ä§î?"
#define sz_pmt_move		"§±§Ö§â§Ö§Þ§Ö-\n§ã§ä§Ú§ä§î?"
#define sz_pmt_stop		"§±§â§Ö§â§Ó§Ñ§ä§î?"
#define sz_pmt_cancel	"§°§é§Ú§ã§ä§Ú§ä§î §Ò§å§æ§Ö§â?"
#define sz_pmt_exists	"§¶§Ñ§Û§Ý §ã§å§ë§Ö§ã§ä§Ó§å§Ö§ä. §©§Ñ§Þ§Ö§ß§Ú§ä§î?"
#define sz_pmt_exit		"§£§í§Û§ä§Ú §Ú§Ù MC?"
#define sz_pmt_impcs	"§±§â§Ú§Þ§Ö§ß§Ú§ä§î §è§Ó§Ö§ä§à§Ó§å§ð §ã§ç§Ö§Þ§å?"
#define sz_pmt_implg	"§±§â§Ú§Þ§Ö§ß§Ú§ä§î §ñ§Ù§í§Ü?"

#define sz_err_attrset		"§¯§Ö §å§Õ§Ñ§Ý§à§ã§î §Ù§Ñ§Õ§Ñ§ä§î §Ñ§ä§â§Ú§Ò§å§ä§í!"
#define sz_err_makedir		"§¯§Ö §å§Õ§Ñ§Ý§à§ã§î §ã§à§Ù§Õ§Ñ§ä§î §á§Ñ§á§Ü§å!"
#define sz_err_rename		"§¯§Ö §å§Õ§Ñ§Ý§à§ã§î §á§Ö§â§Ö§Ú§Þ§Ö-\n§ß§à§Ó§Ñ§ä§î!"
#define sz_err_delete		"§¯§Ö §å§Õ§Ñ§Ý§à§ã§î §å§Õ§Ñ§Ý§Ú§ä§î!"
#define sz_err_badname_t	"§¯§Ö§Ó§Ö§â§ß§à§Ö §Ú§Þ§ñ: %t"
#define sz_err_baddrv_t		"§¯§Ö§Ó§Ö§â§ß§í§Û §Õ§Ú§ã§Ü! %t"
#define sz_err_resnok		"§£§í§á§à§Ý§ß§Ö§ß§à §ã §à§ê§Ú§Ò§Ü§Ñ§Þ§Ú!"
#define sz_err_nofiles		"§¯§Ö§ä §æ§Ñ§Û§Ý§à§Ó!"
#define sz_err_badname		"§¯§Ö§Ó§Ö§â§ß§à§Ö §Ú§Þ§ñ!"
#define sz_err_badkey		"§°§ê§Ú§Ò§Ü§Ñ §Ü§à§ß§æ§Ú§Ô§å§â§Ñ§è§Ú§Ú §Ü§ß§à§á§à§Ü!"
#define sz_err_badformat	"§¯§Ö§Ó§Ö§â§ß§í§Û §æ§à§â§Þ§Ñ§ä §Ú§Ý§Ú §æ§Ñ§Û§Ý §á§à§Ó§â§Ö§Ø§Õ§Ö§ß!"
#define sz_err_nomemory		"§¯§Ö §ç§Ó§Ñ§ä§Ñ§Ö§ä §á§Ñ§Þ§ñ§ä§Ú!"
#define sz_err_makefile		"§¯§Ö §å§Õ§Ñ§Ý§à§ã§î §ã§à§Ù§Õ§Ñ§ä§î §ß§à§Ó§í§Û §æ§Ñ§Û§Ý!"
#define sz_err_ziperr		"§°§ê§Ú§Ò§Ü§Ñ Zip: %d §Ó %t!"

#define sz_msg_zreading			"§¹§ä§Ö§ß§Ú§Ö §Ñ§â§ç§Ú§Ó§Ñ"
#define sz_msg_showhid_files	"§±§à§Ü§Ñ§Ù§í§Ó§Ñ§ä§î §ã§Ü§â§í§ä§í§Ö §æ§Ñ§Û§Ý§í"
#define sz_msg_showsys_files	"§±§à§Ü§Ñ§Ù§í§Ó§Ñ§ä§î §ã§Ú§ã§ä§Ö§Þ§ß§í§Ö §æ§Ñ§Û§Ý§í"
#define sz_msg_showhidsys_files	"§±§à§Ü§Ñ§Ù§í§Ó§Ñ§ä§î §ã§Ü§â§í§ä§í§Ö §Ú §ã§Ú§ã§ä§Ö§Þ§ß§í§Ö §æ§Ñ§Û§Ý§í"
#define sz_msg_showhid_drv		"§±§à§Ü§Ñ§Ù§í§Ó§Ñ§ä§î §ã§Ü§â§í§ä§í§Ö §Õ§Ú§ã§Ü§Ú"

#endif
